datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    db: 
      driver: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}
    
ebean:
  migration:
    run: true    
