datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    platform: postgres
    ddlMode: dropCreate
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true

